services:
  Mooc.Courses.application.CourseCreator:
    classs: ../../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: []
  
  Mooc.Courses.domain.CourseRepository:
    class: ../
